import os

env = Environment(
CCFLAGS = ['-g', '-Wall'],
#CPPPATH = ['../include', '/usr/src/gtest/'],
CPPPATH = ['../include', '../gtest/gtest-1.7.0', '../gtest/gtest-1.7.0/include'],
LIBPATH = '../lib',
LIBS = ['isl', 'pthread', 'rt']
)
env.Append(ENV = {'PATH' : os.environ['PATH']})

# TODO: To be ported to GTest/GMock:
datetimeTestBuilder = env.Program('datetime/datetime', Glob('datetime/main.cxx'))
timerTestBuilder = env.Program('timer/timer', Glob('timer/main.cxx'))
httpTestBuilder = env.Program('http/http', Glob('http/main.cxx'))
threadTestBuilder = env.Program('thread/thread', Glob('thread/main.cxx'))
logTestBuilder = env.Program('log', 'log.cxx')

datetimeTestBuilder1 = env.Program('dt', ['datetime.cxx', 'gtest.cxx'])
testHttpBuilder = env.Program('test_http', ['http/test_http.cxx', 'http/HttpMessageComposer.cxx', 'http/http_headers_test.cxx', 'gtest.cxx'])

Default([datetimeTestBuilder, datetimeTestBuilder1, timerTestBuilder, httpTestBuilder, threadTestBuilder, logTestBuilder, testHttpBuilder])
