import os

env = Environment(
CCFLAGS = ['-g', '-Wall'],
CPPPATH = '../../include',
LIBPATH = '../../lib',
LIBS = ['isl', 'pthread', 'rt']
)
env.Append(ENV = {'PATH' : os.environ['PATH']})

programBuilder = env.Program('test', Glob('*.cxx'))
Default(programBuilder)
