import os

env = Environment(
CCFLAGS = ['-g', '-Wall'],
CPPPATH = '../../include',
LIBPATH = '../../lib',
LIBS = ['isl', 'pthread', 'rt']
)
env.Append(ENV = {'PATH' : os.environ['PATH']})

serverBuilder = env.Program('htcpd', Glob('server/*.cxx'))
clientBuilder = env.Program('htcp', Glob('client/*.cxx'))
Default([serverBuilder, clientBuilder])

