import os

env = Environment(
CCFLAGS = ['-g', '-Wall'],
CPPPATH = ['include', '../../include'],
LIBS = 'dl'
)
env.Append(ENV = {'PATH' : os.environ['PATH']})
env.ParseConfig('pkg-config --cflags --libs libmodbus')

# Build section
staticLibraryBuilder = env.StaticLibrary('../../lib/islScada', Glob('src/*.cxx'))
sharedLibraryBuilder = env.SharedLibrary('../../lib/islScada', Glob('src/*.cxx'))
Default([staticLibraryBuilder, sharedLibraryBuilder])

# Install section
prefix = '/usr/local'
if 'PREFIX' in os.environ:
	prefix = os.environ['PREFIX']
libraryInstaller = env.Install(os.path.join(prefix, 'lib'), [staticLibraryBuilder, sharedLibraryBuilder])
headersInstaller = env.Install(os.path.join(prefix, 'include/isl'), Glob('include/isl/*.hxx'))
env.Alias('install', [libraryInstaller, headersInstaller])
